AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 512

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
  CocNPKFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: coc_npk/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref DataBucket
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          DATA_BUCKET_NAME: !Ref DataBucket
      Events:
        CocNPK:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /coc
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CocNPKApi:
    Description: "API Gateway endpoint URL for Prod stage for CocNPK function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/coc/"
  CocNPKFunction:
    Description: "CocNPK Lambda Function ARN"
    Value: !GetAtt CocNPKFunction.Arn
  CocNPKFunctionIamRole:
    Description: "Implicit IAM Role created for CocNPK function"
    Value: !GetAtt CocNPKFunctionRole.Arn
